export const citiesData = [
    {
        image: "https://img.icons8.com/color/512/kenya-circular.png",
        label: "Nairobi",
        value: "nairobi",
        description: "Kenya",
    },

    {
        image: "https://img.icons8.com/color/512/sudan-circular.png",
        label: "Khartum",
        value: "khartum",
        description: "Sudan",
    },
    {
        image: "https://img.icons8.com/color/512/south-africa-circular.png",
        label: "Cape Town",
        value: "capetown",
        description: "South Africa",
    },
    {
        image: "https://img.icons8.com/color/512/botswana-circular.png",
        label: "Gaborone",
        value: "gaborone",
        description: "Botswana",
    },
];

export const dummyUsers = [
    {
        _id: {},
        username: "samuser1",
        email: "",
        password: "",
        name: "sam1",
        fathers_name: "",
        last_name: "",
        nicknames: [],
        current_location: "",
        birth_place: "",
        birthday: "",
        parents: {
            father: "",
            mother: "",
            step_father: [],
            step_mother: [],
        },
        path: "",
        children: {
            sons: [],
            daughters: [],
            step_sons: [],
            step_daughters: [],
        },
        relatives: [],
        pic_url: "",
        claimed: true,
    },
    {
        _id: {},
        username: "samuser2",
        email: "",
        password: "",
        name: "sam2",
        fathers_name: "",
        last_name: "",
        nicknames: [],
        current_location: "",
        birth_place: "",
        birthday: "",
        parents: {
            father: "639a14b0c63401604d62a97d",
            mother: "",
            step_father: [],
            step_mother: [],
        },
        path: ",639a14b0c63401604d62a97d,",
        children: {
            sons: [],
            daughters: [],
            step_sons: [],
            step_daughters: [],
        },
        relatives: [],
        pic_url: "",
        claimed: true,
        ancestors: ["639a14b0c63401604d62a97d"],
    },
    {
        _id: {},
        username: "samuser3",
        email: "",
        password: "",
        name: "sam3",
        fathers_name: "",
        last_name: "",
        nicknames: [],
        current_location: "",
        birth_place: "",
        birthday: "",
        parents: {
            father: "639a14b0c63401604d62a97d",
            mother: "",
            step_father: [],
            step_mother: [],
        },
        path: ",639a14b0c63401604d62a97d,",
        children: {
            sons: [],
            daughters: [],
            step_sons: [],
            step_daughters: [],
        },
        relatives: [],
        pic_url: "",
        claimed: true,
        ancestors: ["639a14b0c63401604d62a97d"],
    },
    {
        _id: {},
        username: "samuser4",
        email: "",
        password: "",
        name: "sam4",
        fathers_name: "",
        last_name: "",
        nicknames: [],
        current_location: "",
        birth_place: "",
        birthday: "",
        parents: {
            father: "639a14b0c63401604d62a97d",
            mother: "",
            step_father: [],
            step_mother: [],
        },
        path: ",639a14b0c63401604d62a97d,",
        children: {
            sons: [],
            daughters: [],
            step_sons: [],
            step_daughters: [],
        },
        relatives: [],
        pic_url: "",
        claimed: true,
        ancestors: ["639a14b0c63401604d62a97d"],
    },
    {
        _id: {},
        username: "samuser5",
        email: "",
        password: "",
        name: "sam5",
        fathers_name: "",
        last_name: "",
        nicknames: [],
        current_location: "",
        birth_place: "",
        birthday: "",
        parents: {
            father: "639a14b0c63401604d62a97e",
            mother: "",
            step_father: [],
            step_mother: [],
        },
        path: ",639a14b0c63401604d62a97d,639a14b0c63401604d62a97e,",
        children: {
            sons: [],
            daughters: [],
            step_sons: [],
            step_daughters: [],
        },
        relatives: [],
        pic_url: "",
        claimed: true,
        ancestors: ["639a14b0c63401604d62a97d", "639a14b0c63401604d62a97e"],
    },
    {
        _id: {},
        username: "samuser6",
        email: "",
        password: "",
        name: "sam6",
        fathers_name: "",
        last_name: "",
        nicknames: [],
        current_location: "",
        birth_place: "",
        birthday: "",
        parents: {
            father: "639a14b0c63401604d62a97e",
            mother: "",
            step_father: [],
            step_mother: [],
        },
        path: ",639a14b0c63401604d62a97d,639a14b0c63401604d62a97e,",
        children: {
            sons: [],
            daughters: [],
            step_sons: [],
            step_daughters: [],
        },
        relatives: [],
        pic_url: "",
        claimed: true,
        ancestors: ["639a14b0c63401604d62a97d", "639a14b0c63401604d62a97e"],
    },
    {
        _id: {},
        username: "samuser7",
        email: "",
        password: "",
        name: "sam7",
        fathers_name: "",
        last_name: "",
        nicknames: [],
        current_location: "",
        birth_place: "",
        birthday: "",
        parents: {
            father: "639a14b0c63401604d62a97f",
            mother: "",
            step_father: [],
            step_mother: [],
        },
        path: ",639a14b0c63401604d62a97d,639a14b0c63401604d62a97f,",
        children: {
            sons: [],
            daughters: [],
            step_sons: [],
            step_daughters: [],
        },
        relatives: [],
        pic_url: "",
        claimed: true,
        ancestors: ["639a14b0c63401604d62a97d", "639a14b0c63401604d62a97f"],
    },
    {
        _id: {},
        username: "samuser8",
        email: "",
        password: "",
        name: "sam8",
        fathers_name: "",
        last_name: "",
        nicknames: [],
        current_location: "",
        birth_place: "",
        birthday: "",
        parents: {
            father: "639a14b0c63401604d62a97f",
            mother: "",
            step_father: [],
            step_mother: [],
        },
        path: ",639a14b0c63401604d62a97d,639a14b0c63401604d62a97f,",
        children: {
            sons: [],
            daughters: [],
            step_sons: [],
            step_daughters: [],
        },
        relatives: [],
        pic_url: "",
        claimed: true,
        ancestors: ["639a14b0c63401604d62a97d", "639a14b0c63401604d62a97f"],
    },
    {
        _id: {},
        username: "samuser9",
        email: "",
        password: "",
        name: "sam9",
        fathers_name: "",
        last_name: "",
        nicknames: [],
        current_location: "",
        birth_place: "",
        birthday: "",
        parents: {
            father: "639a14b0c63401604d62a980",
            mother: "",
            step_father: [],
            step_mother: [],
        },
        path: ",639a14b0c63401604d62a97d,639a14b0c63401604d62a980,",
        children: {
            sons: [],
            daughters: [],
            step_sons: [],
            step_daughters: [],
        },
        relatives: [],
        pic_url: "",
        claimed: true,
        ancestors: ["639a14b0c63401604d62a97d", "639a14b0c63401604d62a980"],
    },
    {
        _id: {},
        name: "newatran",
        email: "atranarsenal@gmail.com",
        image: "https://avatars.githubusercontent.com/u/15000399?v=4",
        emailVerified: null,
        birth_place: "",
        birthday: "",
        children: {
            sons: [],
            daughters: [],
            step_sons: [],
            step_daughters: [],
        },
        claimed: true,
        current_location: "",
        fathers_name: "",
        last_name: "",
        nicknames: "atu",
        parents: {
            father: "",
            mother: "",
            step_father: [],
            step_mother: [],
        },
        path: "",
        relatives: [],
    },
];
