const m = {
    name: req.body.name,
    nicknames: req.body.nicknames,
    fathers_name: "",
    last_name: "",
    current_location: "",
    birth_place: "",
    birthday: "",
    parents: {
        father: "",
        mother: "",
        step_father: [],
        step_mother: [],
    },
    path: "",
    children: {
        sons: [],
        daughters: [],
        step_sons: [],
        step_daughters: [],
    },
    relatives: [],
    claimed: true,
};
/** +++++++++++++++++++++++++++++++++++++++++++++++++++++++ */
const newPopulation = [
    {
        name: "Jeffery",
        nicknames: "",
        fathers_name: "Lewis",
        last_name: "",
        current_location: "",
        birth_place: "",
        birthday: "",
        parents: {
            father: "",
            mother: "",
            step_father: [],
            step_mother: [],
        },
        path: "",
        children: {
            sons: [],
            daughters: [],
            step_sons: [],
            step_daughters: [],
        },
        relatives: [],
        owner: "63a69bcff12f9e9b13b9ec48",
    },
    {
        name: "Jamison",
        nicknames: "",
        fathers_name: "Patrick",
        last_name: "",
        current_location: "",
        birth_place: "",
        birthday: "",
        parents: {
            father: "",
            mother: "",
            step_father: [],
            step_mother: [],
        },
        path: "",
        children: {
            sons: [],
            daughters: [],
            step_sons: [],
            step_daughters: [],
        },
        relatives: [],
        owner: "63a69bcff12f9e9b13b9ec48",
    },
    {
        name: "Aylin",
        nicknames: "",
        fathers_name: "Farrell",
        last_name: "",
        current_location: "",
        birth_place: "",
        birthday: "",
        parents: {
            father: "",
            mother: "",
            step_father: [],
            step_mother: [],
        },
        path: "",
        children: {
            sons: [],
            daughters: [],
            step_sons: [],
            step_daughters: [],
        },
        relatives: [],
        owner: "63a69bcff12f9e9b13b9ec48",
    },
    {
        name: "Jamison",
        nicknames: "",
        fathers_name: "Patrick",
        last_name: "",
        current_location: "",
        birth_place: "",
        birthday: "",
        parents: {
            father: "",
            mother: "",
            step_father: [],
            step_mother: [],
        },
        path: "",
        children: {
            sons: [],
            daughters: [],
            step_sons: [],
            step_daughters: [],
        },
        relatives: [],
        owner: "63a69bcff12f9e9b13b9ec48",
    },
    {
        name: "Lillie",
        nicknames: "",
        fathers_name: "Palmer",
        last_name: "",
        current_location: "",
        birth_place: "",
        birthday: "",
        parents: {
            father: "",
            mother: "",
            step_father: [],
            step_mother: [],
        },
        path: "",
        children: {
            sons: [],
            daughters: [],
            step_sons: [],
            step_daughters: [],
        },
        relatives: [],
        owner: "63a69bcff12f9e9b13b9ec48",
    },
    {
        name: "Pierce",
        nicknames: "",
        fathers_name: "Mooney",
        last_name: "",
        current_location: "",
        birth_place: "",
        birthday: "",
        parents: {
            father: "",
            mother: "",
            step_father: [],
            step_mother: [],
        },
        path: "",
        children: {
            sons: [],
            daughters: [],
            step_sons: [],
            step_daughters: [],
        },
        relatives: [],
        owner: "63a69bcff12f9e9b13b9ec48",
    },
    {
        name: "Bethany",
        nicknames: "",
        fathers_name: "James",
        last_name: "",
        current_location: "",
        birth_place: "",
        birthday: "",
        parents: {
            father: "",
            mother: "",
            step_father: [],
            step_mother: [],
        },
        path: "",
        children: {
            sons: [],
            daughters: [],
            step_sons: [],
            step_daughters: [],
        },
        relatives: [],
        owner: "63a69bcff12f9e9b13b9ec48",
    },
    {
        name: "Jensen",
        nicknames: "",
        fathers_name: "Vaughan",
        last_name: "",
        current_location: "",
        birth_place: "",
        birthday: "",
        parents: {
            father: "",
            mother: "",
            step_father: [],
            step_mother: [],
        },
        path: "",
        children: {
            sons: [],
            daughters: [],
            step_sons: [],
            step_daughters: [],
        },
        relatives: [],
        owner: "63a69bcff12f9e9b13b9ec48",
    },
    {
        name: "Gary",
        nicknames: "",
        fathers_name: "Golden",
        last_name: "",
        current_location: "",
        birth_place: "",
        birthday: "",
        parents: {
            father: "",
            mother: "",
            step_father: [],
            step_mother: [],
        },
        path: "",
        children: {
            sons: [],
            daughters: [],
            step_sons: [],
            step_daughters: [],
        },
        relatives: [],
        owner: "63a69bcff12f9e9b13b9ec48",
    },
    {
        name: "Georgia",
        nicknames: "",
        fathers_name: "Gilbert",
        last_name: "",
        current_location: "",
        birth_place: "",
        birthday: "",
        parents: {
            father: "",
            mother: "",
            step_father: [],
            step_mother: [],
        },
        path: "",
        children: {
            sons: [],
            daughters: [],
            step_sons: [],
            step_daughters: [],
        },
        relatives: [],
        owner: "63a69bcff12f9e9b13b9ec48",
    },
];
const a = {
    name: "newatran",
    email: "atranarsenal@gmail.com",
    image: "https://avatars.githubusercontent.com/u/15000399?v=4",
    emailVerified: null,
    birth_place: "",
    birthday: "",
    children: {
        sons: [],
        daughters: [],
        step_sons: [],
        step_daughters: [],
    },
    owner: "self", //either self or user object id
    current_location: "",
    fathers_name: "",
    last_name: "",
    nicknames: "atu",
    parents: {
        father: "",
        mother: "",
        step_father: [],
        step_mother: [],
    },
    path: "",
    relatives: [],
    ancestors: [],
};
